services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=servidorr'
      - 'POSTGRES_PASSWORD=MyPassword'
      - 'POSTGRES_USER=postgres1'
    ports:
      - '5433:5432'
